name: Update Contributors

on:
  pull_request:
    types:
      - opened

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Secret
        run: echo ${{ secrets.GH_TOKEN }}

      - name: Fetch Contributors
        run: |
          CONTRIBUTORS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/contributors")
          echo "$CONTRIBUTORS" > contributors.json

      - name: Update README
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: main
          build_dir: .
          commit_message: "[actions] Update contributors"
          files: |
            contributors.json
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Contributors Section
        run: node generate_contributors.js
